@Ordering.Api_HostAddress = http://localhost:6582

POST {{Ordering.Api_HostAddress}}/orders
Accept: application/json
Content-Type: application/json

{
  "quantity": 2,
  "productId": "6f3a38a9-dc22-4876-bc3d-bf66fbc26bc1"
}
###
GET {{Ordering.Api_HostAddress}}/metrics
Accept: application/json

###
GET {{Ordering.Api_HostAddress}}/health
Accept: application/json